<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Scrutor" Version="4.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\building-blocks\Pessoa.Contracts\Pessoa.Contracts.csproj" />
    <ProjectReference Include="..\PessoaWrite.Domain\PessoaWrite.Domain.csproj" />
  </ItemGroup>

</Project>
